### ISSUE TITLE
Waiting for emails based on Subject doesn't work - error: UID command error: BAD [b'expected search-key instead of "{5}<search_term>']

### ISSUE THREAD

**Issue by horzuff** [lasselindqvist/robotframework-imaplibrary#27]
Since the UTF8 subject encoding fix was merged all my "Wait for email" based on Subject are failing with following error. Seems as if the subject is not being provided properly to the underlying python lib. My guess would be, that it has something to do with the fact, that for the SUBJECT criterion the string value is not interpolated as for other text based criteria:

![image](https://user-images.githubusercontent.com/63282033/178977477-c15110d0-2323-4d47-beca-e77afcec353c.png)

Example extract from a robot framework log

KEYWORD ${email} = ImapLibrary2 . Wait For Email subject=${subject}, timeout=${timeout}, status=UNSEEN
Documentation:	
Wait for email message to arrived base on any given filter criteria. Returns email index of the latest email message received.

Start / End / Elapsed:	20220712 09:56:03.809 / 20220712 09:56:03.996 / 00:00:00.187
09:56:03.809	TRACE	Arguments: [ subject="'Job'" | timeout='600' | status='UNSEEN' ]	
09:56:03.996	FAIL	error: UID command error: BAD [b'expected search-key instead of "{5}\\\'JOB\\\'"']	
09:56:03.996	DEBUG	Traceback (most recent call last):
  File "path\venv\lib\site-packages\ImapLibrary2\__init__.py", line 382, in wait_for_email
    self._mails = self._check_emails(**kwargs)
  File "path\venv\lib\site-packages\ImapLibrary2\__init__.py", line 433, in _check_emails
    typ, msgnums = self._imap.uid('search', None, *criteria)
  File "path\Python\Python39\lib\imaplib.py", line 890, in uid
    typ, dat = self._simple_command(name, command, *args)
  File "path\Python\Python39\lib\imaplib.py", line 1230, in _simple_command
    return self._command_complete(name, self._command(name, *args))
  File "path\Python\Python39\lib\imaplib.py", line 1055, in _command_complete
    raise self.error('%s command error: %s %s' % (name, typ, data))
imaplib.IMAP4.error: UID command error: BAD [b'expected search-key instead of "{5}\\\'JOB\\\'"']

**Comment by lasselindqvist** [comment]
Can you create a PR about this possibly?
