### ISSUE TITLE
error: metadata-generation-failed

### ISSUE THREAD

**Issue by AgustinEncoraOficina** [lasselindqvist/robotframework-imaplibrary#37]
python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Agustin.Colque\AppData\Local\Temp\pip-install-2p_rjkwu\robotframework-imaplibrary2_e0d41649ba174472b4cadb94164dca8f\setup.py", line 33, in <module>
          with codecs.open(join(CWD, 'README.md'), encoding='utf-8') as reader:
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<frozen codecs>", line 918, in open
      FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Agustin.Colque\\AppData\\Local\\Temp\\pip-install-2p_rjkwu\\robotframework-imaplibrary2_e0d41649ba174472b4cadb94164dca8f\\README.md'
      [end of output]

**Comment by lasselindqvist** [comment]
Which version?

**Comment by jaltendorfer** [comment]
The latest version on pypi: 0.4.8

**Comment by lasselindqvist** [comment]
Seems like
"python setup.py sdist bdist_wheel"
creates a package without the README.md
Need to figure out why.

**Comment by lasselindqvist** [comment]
Hopefully fixed in 0.4.9

**Comment by codci** [comment]
@lasselindqvist, 0.4.9 was successfully installed on my end
